export const SUM = 'SUM'
export const SIGNUP = 'SIGNUP'
export const SIGNIN = 'SIGNIN'
export const CHECK_FIELD_VALUE_EXISTS = 'CHECK_FIELD_VALUE_EXISTS'
export const USER_CREATED = 'CREATE_USER'
export const USER_LOGGED = 'USER_LOGGED'
export const SIGNOUT = 'SIGNOUT'
